name: green_heart
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.0+9

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0
  go_router: ^14.6.1
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  auth_buttons: ^3.0.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^11.3.1
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  package_info_plus: ^8.1.1
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.1
  table_calendar: ^3.1.2
  collection: ^1.18.0
  algoliasearch: ^1.27.3
  envied: ^1.0.0
  device_info_plus: ^11.3.0

  cupertino_icons: ^1.0.8

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_ios.png"
  image_path_android: "assets/images/icon_android.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_android.png"
  min_sdk_android: 24

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  envied_generator: ^1.0.0

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/terms_of_use.txt
    - assets/privacy_policy.txt
    - assets/images/icon.png
    - assets/images/icon_android.png
    - assets/images/icon_ios.png
    - assets/images/sakura.png
    - assets/images/leaf.png

  fonts:
    - family: MPLUSRounded1c-Regular
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
    - family: MPLUSRounded1c-Medium
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf
